### ISSUE TITLE
사용자가 게시글 작성 페이지에서 게시글을 작성할 수 있습니다. [IHF-2]

### ISSUE THREAD

**Issue by Jh-jaehyuk** [road-to-employment/interview-helper-frontend#3]
# Success Criteria
1. 사용자가 게시글 작성 페이지에서 게시글을 작성할 수 있습니다.
2. 게시글에는 제목, 작성자, 내용이 포함되어야 합니다.

# To-do
- [x] 사용자가 게시글 목록 페이지에서 게시글 작성 버튼을 눌러, 게시글 작성 페이지로 이동할 수 있어야 합니다.
- [x] 게시글 내용 작성 후, 작성 완료 버튼을 누르면 게시글 목록 페이지로 이동할 수 있어야 합니다.
- [x] 요청이 정상적으로 처리되는지 확인

# Review

# Issue
