### ISSUE TITLE
사용자가 게시글 상세 내용을 조회할 수 있습니다. [IHF-3]

### ISSUE THREAD

**Issue by Jh-jaehyuk** [road-to-employment/interview-helper-frontend#8]
# Success Criteria
1. 사용자가 게시글 목록 페이지에서 게시글을 선택하면 해당 게시글의 상세 내용을 조회할 수 있습니다.
2. 게시글 상세 내용에는 제목, 작성자, 내용이 포함되어야 합니다.

# To-do
- [x] 게시글 목록에서 게시글을 선택하면 게시글 읽기 페이지로 이동할 수 있어야 합니다.
- [x] 게시글 읽기 페이지에서 취소 버튼을 누르면 게시글 목록 페이지로 이동할 수 있어야 합니다.
- [x] 요청이 정상적으로 처리되는지 확인

# Review

# Issue
