### ISSUE TITLE
사용자가 작성한 게시글을 삭제할 수 있습니다. [IHF-4]

### ISSUE THREAD

**Issue by Ah-ram** [road-to-employment/interview-helper-frontend#9]
# Success Criteria
1. 사용자가 게시글 상세 페이지에서 작성한 게시글을 삭제할 수 있습니다.

# To-do
- [x] 사용자가 게시글 상세 페이지에서 삭제 버튼을 눌러, 해당 게시글을 삭제할 수 있어야 합니다.
- [x] 게시글을 삭제한 이후 게시글 목록 페이지로 이동할 수 있어야 합니다.
- [x] 요청이 정상적으로 처리되는지 확인

# Review

# Issue
